# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_df = pd.read_csv("./Resources/weather_df.csv")
weather_df = weather_df[['City', 'Lat', 'Lng', 'Temp', 'Humidity', 'Cloudiness', 'Wind Speed', 'Country', 'Date']]
weather_df.head()

,City,Lat,Lng,Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Albany,42.6001,-73.9662,26.15,87,100,3.06,US,1612901116
1,Mataura,-46.1927,168.8643,48.15,95,100,5.48,NZ,1612901256
2,Alofi,-19.0595,-169.9187,80.60,89,75,8.05,NU,1612901364
3,Ushuaia,-54.8000,-68.3000,64.40,59,40,4.61,AR,1612901264
4,Marsh Harbour,26.5412,-77.0636,76.71,81,24,9.40,BS,1612901635

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)
locations = weather_df[["Lat", "Lng"]]
humidity = weather_df["Humidity"]
fig = gmaps.figure(zoom_level=2, center=(10,0))
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, 
                                 max_intensity=weather_df['Humidity'].max(), point_radius=1)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
ideal_df = weather_df.loc[(weather_df['Temp'] >= 70) & (weather_df['Temp'] <= 76)]
ideal_df = ideal_df.loc[weather_df['Humidity'] < 70]
ideal_df = ideal_df.loc[weather_df['Wind Speed'] < 12]
ideal_df = ideal_df.loc[weather_df['Cloudiness'] < 50]
ideal_df

,City,Lat,Lng,Temp,Humidity,Cloudiness,Wind Speed,Country,Date
71,Araouane,18.9048,-3.5265,72.86,16,32,9.35,ML,1612901322
166,Tombouctou,20.0000,-3.0000,70.27,17,0,9.28,ML,1612901675
232,Cabo San Lucas,22.8909,-109.9124,73.02,60,1,9.22,MX,1612901305
255,Maiduguri,11.8464,13.1603,73.35,19,19,9.17,NG,1612901698
273,Constituci√≥n,-35.3333,-72.4167,70.20,67,13,8.37,CL,1612901287
309,Arlit,18.7369,7.3853,71.73,15,0,3.15,NE,1612901570
318,Gour√©,13.9835,10.2704,74.43,17,0,9.57,NE,1612901639
366,Moussoro,13.6408,16.4901,74.71,16,0,11.74,TD,1612901725
433,Valpara√≠so,-33.0393,-71.6273,70.00,60,20,8.05,CL,1612901297
522,Necochea,-38.5473,-58.7368,70.00,59,8,7.00,AR,1612901571
541,Ixtapa,20.7000,-105.2000,73.40,68,1,11.50,MX,1612901284

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
hotel_df = ideal_df
hotel_df['Hotel Name'] = ""

hotels = []

for index, row in hotel_df.iterrows():
    
    lati = row["Lat"]
    long = row["Lng"]      
    
    params = {
    "location": f"{lati}, {long}",
    "keyword": "hotels",
    "radius": 5000,
    "type": 'lodging',
    "key": g_key
    }
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    response = requests.get(base_url, params=params)
    data = response.json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = data["results"][0]["name"]
    except:
        hotel_df.loc[index, "Hotel Name"] = "No Near Logdging Found"        

hotel_df.head()

,City,Lat,Lng,Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
71,Araouane,18.9048,-3.5265,72.86,16,32,9.35,ML,1612901322,No Near Logdging Found
166,Tombouctou,20.0000,-3.0000,70.27,17,0,9.28,ML,1612901675,No Near Logdging Found
232,Cabo San Lucas,22.8909,-109.9124,73.02,60,1,9.22,MX,1612901305,Hotel Riu Palace Cabo San Lucas
255,Maiduguri,11.8464,13.1603,73.35,19,19,9.17,NG,1612901698,Nanne and Boi Suites
273,Constituci√≥n,-35.3333,-72.4167,70.20,67,13,8.37,CL,1612901287,Posada la Piedra

In [6]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [7]:
# Add marker layer ontop of heat map

markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

# Display figure

Figure(layout=FigureLayout(height='420px'))